### ISSUE TITLE
The program 'basic.exe' crashing constantly

### ISSUE THREAD

**Issue by PeterOSdev** [CadexOS/Cadex-OS-Official#5]
After entering "cd /" and then "./basic.exe" The system restarts. (On qemu-system-i386)

**Comment by asiawin** [comment]
I think it's the problem with some system calls that `basic` uses. I'll try to fix this.

**Comment by asiawin** [comment]
I removed `basic.exe` because it is unnecessary. I think it is a problem with the `syscall_open_file` syscall. If that's the case, then `cat.exe` should also fail as it also uses the same syscall to read the files

**Comment by asiawin** [comment]
> After entering "cd /" and then "./basic.exe" The system restarts. (On qemu-system-i386)

This is fixed now. It was a problem with the function that takes input from the user and processes it.

**Comment by asiawin** [comment]
@PeterOSdev, if you know OS development, you can contribute to this project.
