### ISSUE TITLE
Text hard to read

### ISSUE THREAD

**Issue by PeterOSdev** [CadexOS/Cadex-OS-Official#6]
The output of "ls" in the ISO file (on qemu-system-i386) is dark grey on black. That's hard to read.

**Comment by asiawin** [comment]
I also had this issue.

**Comment by asiawin** [comment]
Trying to resolve this issue. I recently figured out that you could install Cadex OS into the hard disk using the `install` command. After that this bug occurred.

**Comment by asiawin** [comment]
This is fixed and now works fine.
